CREATE TABLE PRODUCT (
                        ID INT NOT NULL AUTO_INCREMENT
    , PRODUCT_NAME VARCHAR(60) NOT NULL
    , PRODUCT_PRICE INT NOT NULL
    , PRODUCT_QUANTITY INT NOT NULL
    , PRIMARY KEY (ID)
);

CREATE TABLE CLIENT (
                       ID INT NOT NULL AUTO_INCREMENT
    , NAME VARCHAR(100) NOT NULL
    , PRODUCT_ID INT NOT NULL
    , EMAIL VARCHAR (100) NOT NULL
                     , PRIMARY KEY (ID),
                       FOREIGN KEY (PRODUCT_ID)
                           REFERENCES PRODUCT (ID)


);

CREATE TABLE SERVICE (
                         ID INT NOT NULL AUTO_INCREMENT
    , TASK VARCHAR(100) NOT NULL
    , PRODUCT_NAME VARCHAR(60) NOT NULL
    , CLIENT_NAME VARCHAR(60) NOT NULL
    , COST INT NOT NULL
    , PRIMARY KEY (ID)
);

